---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nuclei-operator
  namespace: argocd
spec:
  project: "{{ .Values.project }}"
  source:
    repoURL: https://morten-olsen.github.io/homelab-nuclei-operator
    targetRevision: 0.2.9
    chart: nuclei-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{ .Release.Namespace }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

