{{- if .Values.resources.certificate.enabled -}}
{{- $cert := .Values.resources.certificate -}}
{{- $global := .Values.global -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $cert.secretName }}
  namespace: "istio-ingress"
spec:
  secretName: {{ $cert.secretName }}
  issuerRef:
    name: cloudflare-dns
    kind: Issuer
  dnsNames:
  - "*.{{ $global.domain }}"
  - "{{ $global.domain }}"
{{- end }}
