---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: "istio-ingress"
spec:
  secretName: wildcard-tls
  issuerRef:
    name: cloudflare-dns
    kind: Issuer
  dnsNames:
  - "*.{{ .Values.domain }}"
  - "{{ .Values.domain }}"

