{{- if .Values.resources.certificate.enabled -}}
{{- $cert := .Values.resources.certificate -}}
{{- $global := .Values.global -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $cert.secretName }}
  namespace: "{{ .Release.Namespace }}"
spec:
  secretName: {{ $cert.secretName }}
  issuerRef:
    name: cloudflare-dns
    kind: Issuer
  dnsNames:
  - "*.{{ $global.domain }}"
  - "{{ $global.domain }}"
  secretTemplate:
    annotations:
      reflector.v1beta1.emberstack.com/reflection-allowed: "true"
      reflector.v1beta1.emberstack.com/reflection-allowed-namespaces: "istio-ingress"
{{- end }}
