---
# IngressClass for Istio - enables Kubernetes Ingress resources to work with Istio Gateway
# Applications can use standard Ingress resources with ingressClassName: istio
# For automatic TLS, add cert-manager annotations (see example below)
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: istio.io/ingress-controller

