---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-password
  namespace: "{{ .Release.Namespace }}"
spec:
  target:
    name: pihole-password
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pihole-password-generator
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: pihole-password-generator
spec:
  length: 32
  allowRepeat: false
  noUpper: false
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-dns-hmac-secret
  namespace: "{{ .Release.Namespace }}"
spec:
  target:
    name: pihole-dns-hmac-secret
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pihole-dns-hmac-generator
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: pihole-dns-hmac-generator
spec:
  length: 32
  allowRepeat: false
  noUpper: false
  secretKeys:
    - hmac-secret
