{{- if .Values.resources.gateways.private.enabled -}}
{{- $gw := .Values.resources.gateways.private -}}
{{- $cert := .Values.resources.certificate -}}
{{- include "homelab-shared.gateway" (dict "name" "private" "httpPort" $gw.httpPort "httpsPort" $gw.httpsPort "tlsSecretName" $cert.secretName "namespace" .Release.Namespace) }}
{{- end }}