{{- if .Values.resources.gateways.public.enabled -}}
{{- $gw := .Values.resources.gateways.public -}}
{{- $cert := .Values.resources.certificate -}}
{{- include "homelab-shared.gateway" (dict "name" "public" "httpPort" $gw.httpPort "httpsPort" $gw.httpsPort "tlsSecretName" $cert.secretName "namespace" .Release.Namespace) }}
{{- end }}