apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prod
  namespace: "{{ .Release.Namespace }}"
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  backupTargetName: default
  dataEngine: v1
  dataLocality: disabled
  disableRevisionCounter: "true"
  unmapMarkSnapChainRemoved: ignored
allowVolumeExpansion: true
