apiVersion: v2
name: homelab-core
description: Core operators for homelab Kubernetes cluster
version: 0.1.0
appVersion: "1.0"
keywords:
  - homelab
  - kubernetes
  - operators
home: https://github.com/morten-olsen/homelab-core
sources:
  - https://github.com/morten-olsen/homelab-core
