apiVersion: v2
name: homelab-shared
description: Shared resources for homelab Kubernetes cluster
version: 0.1.0
appVersion: "1.0"
keywords:
  - homelab
  - kubernetes
  - shared
  - gateway
  - istio
home: https://github.com/morten-olsen/homelab-core
sources:
  - https://github.com/morten-olsen/homelab-core
